export const URLS = {
    LOGIN_URL   : '/login',
    REGISTER_URL: '/register',
};

export const LOGIN_ERROR_CODES = {
    INVALID_EMAIL   : 'INVALID_EMAIL',
    EMAIL_NOT_FOUND : 'EMAIL_NOT_FOUND',
    INVALID_PASSWORD: 'INVALID_PASSWORD',
    USER_DISABLED   : 'USER_DISABLED',
};

export const REGISTER_ERROR_CODES = {
    INVALID_EMAIL  : 'INVALID_EMAIL',
    EMAIL_NOT_FOUND: 'EMAIL_NOT_FOUND',
    EMAIL_EXISTS   : 'EMAIL_EXISTS',
};
